name: Find and Replace Href File Extension

# only trigger on pull request closed events
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    
jobs:
  deploy_on_pi:
    name: Deploy to deb12Server
    if: github.event.pull_request.merged == true
  
    runs-on: [self-hosted, linux, X64]
    
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v6
        with:
          ref: main
      - name: Change directory to path of Java Archive and run GitHubActionFindAndReplace.jar
        run: |
          cd /var/lkrampitz.net/actions-runner/_lkrampitz.net_work/lkrampitz.net/lkrampitz.net/tools/Java/GitHubActionFindAndReplace/dist
          java -jar GitHubActionFindAndReplace.jar "/var/lkrampitz.net/actions-runner/_lkrampitz.net_work/lkrampitz.net/lkrampitz.net/www" ".html\" data-remove-file-extension=\"true\"" "\" data-remove-file-extension=\"true\""
        shell: bash
